#ifndef __KEYCODES_H__
#define __KEYCODES_H__

/* Alt + Row1 */

#define KDX_KEY_1	2
#define KDX_KEY_2	3
#define KDX_KEY_3	4
#define KDX_KEY_4	5
#define KDX_KEY_5	6
#define KDX_KEY_6	7
#define KDX_KEY_7	8
#define KDX_KEY_8	9
#define KDX_KEY_9	10
#define KDX_KEY_0	11

/* Row1 */
#define KDX_KEY_Q	16
#define KDX_KEY_W	17
#define KDX_KEY_E	18
#define KDX_KEY_R	19
#define KDX_KEY_T	20
#define KDX_KEY_Y	21
#define KDX_KEY_U	22
#define KDX_KEY_I	23
#define KDX_KEY_O	24
#define KDX_KEY_P	25

/* Row2 */
#define KDX_KEY_A	30
#define KDX_KEY_S	31
#define KDX_KEY_D	32
#define KDX_KEY_F	33
#define KDX_KEY_G	34
#define KDX_KEY_H	35
#define KDX_KEY_J	36
#define KDX_KEY_K	37
#define KDX_KEY_L	38
#define KDX_KEY_DEL	14

/* Row3 */
#define KDX_KEY_Z	44
#define KDX_KEY_X	45
#define KDX_KEY_C	46
#define KDX_KEY_V	47
#define KDX_KEY_B	48
#define KDX_KEY_N	49
#define KDX_KEY_M	50
#define KDX_KEY_DOT	52
#define KDX_KEY_SLASH	53
#define KDX_KEY_ENTER	28

/* Row4 */
#define KDX_KEY_SHIFT	42
#define KDX_KEY_ALT	56
#define KDX_KEY_SPACE	57
#define KDX_KEY_AA	90
#define KDX_KEY_SYM	94
//
#define K3_KEY_AA	190
#define K3_KEY_SYM	126
#define K3_KEY_HOME	102
#define K3_KEY_BACK	158

/* Edge */
#define KDX_KEY_VPLUS	115
#define KDX_KEY_VMINUS	114
#define KDX_KEY_HOME	98
#define KDX_KEY_PAGEUP	109
#define KDX_KEY_PAGEDN	124
#define KDX_KEY_MENU	139
#define KDX_KEY_BACK	91
//
#define K3_KEY_PAGEDN	191
#define K3_KEY_LPAGEUP	193
#define K3_KEY_LPAGEDN	104
//
// same codes as on DXG, but generated by dev/input/event2
#define K3_KEY_VPLUS	115
#define K3_KEY_VMINUS	114

/* FiveWay manipulator */
#define KDX_KEY_LARROW	105
#define KDX_KEY_RARROW	106
#define KDX_KEY_UPARROW	122
#define KDX_KEY_DNARROW	123
#define KDX_KEY_5WPRESS	92
//
#define K3_KEY_UPARROW	103
#define K3_KEY_DNARROW	108
#define K3_KEY_5WPRESS	194

// Kindle 4 NT
#define K4_KEY_KBD	29

#endif	/* __KEYCODES_H__ */


